//Generated Key Mappings
if (ass[pos]==0){keyboard_keys[keycount++] = KEY_NONE;}
if (ass[pos]==1){keyboard_keys[keycount++] = KEY_A;}
if (ass[pos]==2){keyboard_keys[keycount++] = KEY_B;}
if (ass[pos]==3){keyboard_keys[keycount++] = KEY_C;}
if (ass[pos]==4){keyboard_keys[keycount++] = KEY_D;}
if (ass[pos]==5){keyboard_keys[keycount++] = KEY_E;}
if (ass[pos]==6){keyboard_keys[keycount++] = KEY_F;}
if (ass[pos]==7){keyboard_keys[keycount++] = KEY_G;}
if (ass[pos]==8){keyboard_keys[keycount++] = KEY_H;}
if (ass[pos]==9){keyboard_keys[keycount++] = KEY_I;}
if (ass[pos]==10){keyboard_keys[keycount++] = KEY_J;}
if (ass[pos]==11){keyboard_keys[keycount++] = KEY_K;}
if (ass[pos]==12){keyboard_keys[keycount++] = KEY_L;}
if (ass[pos]==13){keyboard_keys[keycount++] = KEY_M;}
if (ass[pos]==14){keyboard_keys[keycount++] = KEY_N;}
if (ass[pos]==15){keyboard_keys[keycount++] = KEY_O;}
if (ass[pos]==16){keyboard_keys[keycount++] = KEY_P;}
if (ass[pos]==17){keyboard_keys[keycount++] = KEY_Q;}
if (ass[pos]==18){keyboard_keys[keycount++] = KEY_R;}
if (ass[pos]==19){keyboard_keys[keycount++] = KEY_S;}
if (ass[pos]==20){keyboard_keys[keycount++] = KEY_T;}
if (ass[pos]==21){keyboard_keys[keycount++] = KEY_U;}
if (ass[pos]==22){keyboard_keys[keycount++] = KEY_V;}
if (ass[pos]==23){keyboard_keys[keycount++] = KEY_W;}
if (ass[pos]==24){keyboard_keys[keycount++] = KEY_X;}
if (ass[pos]==25){keyboard_keys[keycount++] = KEY_Y;}
if (ass[pos]==26){keyboard_keys[keycount++] = KEY_Z;}
if (ass[pos]==27){keyboard_keys[keycount++] = KEY_1;}
if (ass[pos]==28){keyboard_keys[keycount++] = KEY_2;}
if (ass[pos]==29){keyboard_keys[keycount++] = KEY_3;}
if (ass[pos]==30){keyboard_keys[keycount++] = KEY_4;}
if (ass[pos]==31){keyboard_keys[keycount++] = KEY_5;}
if (ass[pos]==32){keyboard_keys[keycount++] = KEY_6;}
if (ass[pos]==33){keyboard_keys[keycount++] = KEY_7;}
if (ass[pos]==34){keyboard_keys[keycount++] = KEY_8;}
if (ass[pos]==35){keyboard_keys[keycount++] = KEY_9;}
if (ass[pos]==36){keyboard_keys[keycount++] = KEY_0;}
if (ass[pos]==37){keyboard_keys[keycount++] = KEY_ENTER;}
if (ass[pos]==38){keyboard_keys[keycount++] = KEY_ESC;}
if (ass[pos]==39){keyboard_keys[keycount++] = KEY_BACKSPACE;}
if (ass[pos]==40){keyboard_keys[keycount++] = KEY_TAB;}
if (ass[pos]==41){keyboard_keys[keycount++] = KEY_SPACE;}
if (ass[pos]==42){keyboard_keys[keycount++] = KEY_MINUS;}
if (ass[pos]==43){keyboard_keys[keycount++] = KEY_EQUAL;}
if (ass[pos]==44){keyboard_keys[keycount++] = KEY_LEFT_BRACE;}
if (ass[pos]==45){keyboard_keys[keycount++] = KEY_RIGHT_BRACE;}
if (ass[pos]==46){keyboard_keys[keycount++] = KEY_BACKSLASH;}
if (ass[pos]==47){keyboard_keys[keycount++] = KEY_NUMBER;}
if (ass[pos]==48){keyboard_keys[keycount++] = KEY_SEMICOLON;}
if (ass[pos]==49){keyboard_keys[keycount++] = KEY_QUOTE;}
if (ass[pos]==50){keyboard_keys[keycount++] = KEY_TILDE;}
if (ass[pos]==51){keyboard_keys[keycount++] = KEY_COMMA;}
if (ass[pos]==52){keyboard_keys[keycount++] = KEY_PERIOD;}
if (ass[pos]==53){keyboard_keys[keycount++] = KEY_SLASH;}
if (ass[pos]==54){keyboard_keys[keycount++] = KEY_CAPS_LOCK;}
if (ass[pos]==55){keyboard_keys[keycount++] = KEY_F1;}
if (ass[pos]==56){keyboard_keys[keycount++] = KEY_F2;}
if (ass[pos]==57){keyboard_keys[keycount++] = KEY_F3;}
if (ass[pos]==58){keyboard_keys[keycount++] = KEY_F4;}
if (ass[pos]==59){keyboard_keys[keycount++] = KEY_F5;}
if (ass[pos]==60){keyboard_keys[keycount++] = KEY_F6;}
if (ass[pos]==61){keyboard_keys[keycount++] = KEY_F7;}
if (ass[pos]==62){keyboard_keys[keycount++] = KEY_F8;}
if (ass[pos]==63){keyboard_keys[keycount++] = KEY_F9;}
if (ass[pos]==64){keyboard_keys[keycount++] = KEY_F10;}
if (ass[pos]==65){keyboard_keys[keycount++] = KEY_F11;}
if (ass[pos]==66){keyboard_keys[keycount++] = KEY_F12;}
if (ass[pos]==67){keyboard_keys[keycount++] = KEY_PRINTSCREEN;}
if (ass[pos]==68){keyboard_keys[keycount++] = KEY_SCROLL_LOCK;}
if (ass[pos]==69){keyboard_keys[keycount++] = KEY_PAUSE;}
if (ass[pos]==70){keyboard_keys[keycount++] = KEY_INSERT;}
if (ass[pos]==71){keyboard_keys[keycount++] = KEY_HOME;}
if (ass[pos]==72){keyboard_keys[keycount++] = KEY_PAGE_UP;}
if (ass[pos]==73){keyboard_keys[keycount++] = KEY_DELETE;}
if (ass[pos]==74){keyboard_keys[keycount++] = KEY_END;}
if (ass[pos]==75){keyboard_keys[keycount++] = KEY_PAGE_DOWN;}
if (ass[pos]==76){keyboard_keys[keycount++] = KEY_RIGHT;}
if (ass[pos]==77){keyboard_keys[keycount++] = KEY_LEFT;}
if (ass[pos]==78){keyboard_keys[keycount++] = KEY_DOWN;}
if (ass[pos]==79){keyboard_keys[keycount++] = KEY_UP;}
if (ass[pos]==80){keyboard_keys[keycount++] = KEY_NUM_LOCK;}
if (ass[pos]==81){keyboard_keys[keycount++] = KEYPAD_SLASH;}
if (ass[pos]==82){keyboard_keys[keycount++] = KEYPAD_ASTERIX;}
if (ass[pos]==83){keyboard_keys[keycount++] = KEYPAD_MINUS;}
if (ass[pos]==84){keyboard_keys[keycount++] = KEYPAD_PLUS;}
if (ass[pos]==85){keyboard_keys[keycount++] = KEYPAD_ENTER;}
if (ass[pos]==86){keyboard_keys[keycount++] = KEYPAD_1;}
if (ass[pos]==87){keyboard_keys[keycount++] = KEYPAD_2;}
if (ass[pos]==88){keyboard_keys[keycount++] = KEYPAD_3;}
if (ass[pos]==89){keyboard_keys[keycount++] = KEYPAD_4;}
if (ass[pos]==90){keyboard_keys[keycount++] = KEYPAD_5;}
if (ass[pos]==91){keyboard_keys[keycount++] = KEYPAD_6;}
if (ass[pos]==92){keyboard_keys[keycount++] = KEYPAD_7;}
if (ass[pos]==93){keyboard_keys[keycount++] = KEYPAD_8;}
if (ass[pos]==94){keyboard_keys[keycount++] = KEYPAD_9;}
if (ass[pos]==95){keyboard_keys[keycount++] = KEYPAD_0;}
if (ass[pos]==96){keyboard_keys[keycount++] = KEYPAD_PERIOD;}
if (ass[pos]==97){keyboard_keys[keycount++] = KEY_CTRL;}
if (ass[pos]==98){keyboard_keys[keycount++] = KEY_SHIFT;}
if (ass[pos]==99){keyboard_keys[keycount++] = KEY_ALT;}
if (ass[pos]==100){keyboard_keys[keycount++] = KEY_GUI;}
if (ass[pos]==101){keyboard_keys[keycount++] = KEY_LEFT_CTRL;}
if (ass[pos]==102){keyboard_keys[keycount++] = KEY_LEFT_SHIFT;}
if (ass[pos]==103){keyboard_keys[keycount++] = KEY_LEFT_ALT;}
if (ass[pos]==104){keyboard_keys[keycount++] = KEY_LEFT_GUI;}
if (ass[pos]==105){keyboard_keys[keycount++] = KEY_RIGHT_CTRL;}
if (ass[pos]==106){keyboard_keys[keycount++] = KEY_RIGHT_SHIFT;}
if (ass[pos]==107){keyboard_keys[keycount++] = KEY_RIGHT_ALT;}
if (ass[pos]==108){keyboard_keys[keycount++] = KEY_RIGHT_GUI;}
